# Generated by Django 3.0.5 on 2020-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='link',
            field=models.CharField(default='none', max_length=256),
            preserve_default=False,
        ),
    ]
