# Generated by Django 3.0.5 on 2020-04-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20200402_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
