# Generated by Django 3.0.4 on 2020-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_auto_20200409_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='classe_groupe',
            field=models.CharField(max_length=8),
        ),
    ]
