# Generated by Django 3.0.4 on 2020-04-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_auto_20200409_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classe',
            name='classe_groupe',
            field=models.CharField(help_text='Classe concerné par le cours', max_length=8),
        ),
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.BigIntegerField(help_text='Le code du cours pour Zoom'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(help_text='Nom de la classe (matière)', max_length=127),
        ),
    ]
